apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
patchesStrategicMerge:
- deployment.yaml
- service.yaml
replicas:
  - name: vote
    count: 5 
images:
  - name: schoolofdevops/vote
    newTag: v7 # {"$imagepolicy": "flux-system:vote:tag"}
namespace: instavote
commonLabels:
  project: instavote
  env: staging
commonAnnotations:
  supported-by: "sre@example.com"
configMapGenerator:
  - name: voteoptions
    env: options.env

